### ISSUE TITLE
Establecer el tema

### ISSUE THREAD

**Issue by CarlosJChV** [prope-2021-gh-classroom/practica-final-verano-2021-Yuriyama#2]
Escoger un tema en el que podamos aplicar los distintos paquetes requeridos.

**Comment by Yuriyama** [comment]
Carlos, de los que proponen a mí me llamaron la atención el de álgebra lineal en criptografía o el de ecuaciones de Lotka-Volterra. ¿Tú cuáles prefieres? ¿O hay algún otro proyecto en Python que te guste?

**Comment by CarlosJChV** [comment]
Hola Yuriko, a mí también me llama mucho la atención el de álgebra lineal en la criptografía. ¿Quedamos en ese tema?

**Comment by Yuriyama** [comment]
¡Perfecto! Close #2
